name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
#      - name: Setup vuepress


#        uses: pnpm/action-setup@v2
#        with:
#          # 选择要使用的 pnpm 版本
#          version: 8
#          # 使用 pnpm 安装依赖
#          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 16
          # 缓存 pnpm 依赖
#          cache: npm
      - name: Setup vuepress
        run: npm install
#      - name: Setup vue
#        run: npm install -g vue
      # 运行构建脚本
      - name: Build VuePress site
        run:  npm run   build


      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-go-binary:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux, windows, darwin] # 需要打包的系统
          goarch: [amd64, arm64] # 需要打包的架构
          exclude: # 排除某些平台和架构
            - goarch: arm64
              goos: windows
      steps:
        - uses: actions/checkout@v3
        - uses: wangyoucao577/go-release-action@v1.30
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            goversion: 1.18 # 可以指定编译使用的 Golang 版本
            binary_name: "go-cmb-service" # 可以指定二进制文件的名称
            extra_files: README.md config.dev.json # 需要包含的额外文件


 
        
